version: "3.4"

volumes:
  mysql:

services:
  mysql:
    image: boinc/server_mysql:latest
    build: 
      context: ./
      target: mysql
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "3306:3306"

  metricbeat:
      build:
        context: ./metricbeat
        args:
          - METRICBEAT_FILE=metricbeat.yml
          - ELK_HOST=$ELK_HOST
          - HOST_IP=$HOST_IP
      container_name: metricbeat
      depends_on:
        - mysql
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - WAIT_FOR_HOSTS='${ELK_HOST}:9200 ${ELK_HOST}:5601'
        - HOST_ELASTICSEARCH=$ELK_HOST:9200
        - HOST_KIBANA=$ELK_HOST:5601
