metricbeat.modules:
  - module: mysql
    enabled: true
    metricsets: ["status"]
    period: 5s
    hosts: ["root:password@tcp(HOST_IP:3306)/"]

output.elasticsearch:
  hosts: ["ELK_HOST:9200"]
    
setup.kibana:
  host: "ELK_HOST:5601"

setup.dashboards.enabled: true

logging.level: debug
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/metricbeat
  name: metricbeat.log
  keepfiles: 2
  permissions: 0644
